// Talk page strings (docs/UI_SPEC.md A5.3, A5.4, A5.6). English and Spanish hold the same keys.
// Conversation content never lives here: every reply comes from the brain (the sentence bank). The `privacy` line is
// the one place where page text names the browsers' speech services (docs/UI_SPEC.md A0.9).

export const STRINGS = {
  en: {
    title: "Talk to GatorPlate",
    "title.lead": "Talk to",
    "intro.time": "A few minutes. We'll ask about school, home and money — never your Social Security number or immigration status.",
    "intro.mic": "Your browser will ask to use your microphone. You can also type.",
    privacy: "Your browser turns your voice into text (Chrome uses Google's speech service; Safari uses Apple's). GatorPlate only gets the text and never stores audio. We keep your answers and short quotes, not the conversation.",
    start: "Start talking",
    type: "Type instead",
    send: "Send",
    listening: "Listening…",
    thinking: "Thinking…",
    speaking: "GatorPlate is speaking",
    "speaking.tap": "GatorPlate is speaking — tap to interrupt",
    tap_to_talk: "Tap to talk",
    done: "Your card is ready",
    open_card: "Open my card",
    ended: "Conversation ended",
    again: "Start again",
    show_conv: "Show conversation",
    not_recorded: "Not recorded",
    prototype: "Student-built prototype — not an official SF State, county, or CalFresh service.",
    "err.mic_blocked": "Your microphone is blocked. Allow it in the browser (the site settings icon next to the address), or type — it works the same.",
    "err.no_voice": "Voice doesn't work in this browser. Type your answers — it works the same — or open this page in another browser.",
    "err.no_speech": "I didn't catch that. Tap the mic to try again, or type.",
    "err.network": "Voice needs the internet right now. You can type instead.",
    "err.slow": "Still thinking… one moment.",
    "err.server": "Something went wrong. Your answers so far are saved — try again.",
    "err.busy": "Too many people are starting right now. Try again in a few minutes.",
    "err.no_sound": "Can't hear? Turn up the volume.",
    switched: "Switched to English",
    read_aloud: "Read aloud",
    on: "On",
    off: "Off",
    retry: "Try again",
    you: "You",
    gatorplate: "GatorPlate",
    "type.label": "Type your answer",
    "replies.label": "Quick replies",
    "lang.label": "Language",
    home: "GatorPlate home",
    skip: "Skip to the conversation",
    connecting: "One moment…",
    no_js: "This page needs JavaScript to talk with GatorPlate.",
  },
  es: {
    title: "Habla con GatorPlate",
    "title.lead": "Habla con",
    "intro.time": "Unos minutos. Te preguntaremos sobre tus estudios, tu casa y tu dinero; nunca tu número de Seguro Social ni tu estatus migratorio.",
    "intro.mic": "Tu navegador te pedirá usar el micrófono. También puedes escribir.",
    privacy: "Tu navegador convierte tu voz en texto (Chrome usa el servicio de voz de Google; Safari usa el de Apple). GatorPlate solo recibe el texto y nunca guarda audio. Guardamos tus respuestas y citas cortas, no la conversación.",
    start: "Empezar a hablar",
    type: "Escribir",
    send: "Enviar",
    listening: "Escuchando…",
    thinking: "Pensando…",
    speaking: "GatorPlate está hablando",
    "speaking.tap": "GatorPlate está hablando; toca para interrumpir",
    tap_to_talk: "Toca para hablar",
    done: "Tu tarjeta está lista",
    open_card: "Abrir mi tarjeta",
    ended: "Conversación terminada",
    again: "Empezar otra vez",
    show_conv: "Mostrar conversación",
    not_recorded: "No se graba",
    prototype: "Prototipo hecho por estudiantes; no es un servicio oficial de SF State, del condado ni de CalFresh.",
    "err.mic_blocked": "Tu micrófono está bloqueado. Permítelo en el navegador (el ícono de configuración del sitio junto a la dirección) o escribe: funciona igual.",
    "err.no_voice": "La voz no funciona en este navegador. Escribe tus respuestas (funciona igual) o abre esta página en otro navegador.",
    "err.no_speech": "No te escuché. Toca el micrófono para intentar otra vez, o escribe.",
    "err.network": "La voz necesita internet. Puedes escribir.",
    "err.slow": "Sigo pensando… un momento.",
    "err.server": "Algo salió mal. Tus respuestas están guardadas; intenta otra vez.",
    "err.busy": "Hay muchas personas empezando ahora. Intenta otra vez en unos minutos.",
    "err.no_sound": "¿No oyes? Sube el volumen.",
    switched: "Cambiamos a español",
    read_aloud: "Leer en voz alta",
    on: "sí",
    off: "no",
    retry: "Intentar otra vez",
    you: "Tú",
    gatorplate: "GatorPlate",
    "type.label": "Escribe tu respuesta",
    "replies.label": "Respuestas rápidas",
    "lang.label": "Idioma",
    home: "Inicio de GatorPlate",
    skip: "Ir a la conversación",
    connecting: "Un momento…",
    no_js: "Esta página necesita JavaScript para hablar con GatorPlate.",
  },
};

// The language buttons are labeled in their own language (docs/UI_SPEC.md A4.4).
export const LANG_NAMES = { en: "English", es: "Español" };
